package bean;
// Generated Jun 2, 2017 3:55:32 PM by Hibernate Tools 4.3.1



import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Department generated by hbm2java
 */
public class Department implements java.io.Serializable {


     private int depId;
     private String depName;
     private String depPhone;
     private Date founding;
     private String location;
     private String functions;
     private Set<Employee> employees = new HashSet<Employee>(0);

    public Department() {
    }

	
    public Department(int depId) {
        this.depId = depId;
    }
    public Department(int depId, String depName,String depPhone,Date founding,String location,String functions, Set<Employee> employees) {
       this.depId = depId;
       this.depName = depName;
       this.depPhone=depPhone;
       this.founding=founding;
       this.location=location;
       this.functions=functions;
       this.employees = employees;
    }
   
    public int getDepId() {
        return this.depId;
    }
    
    public void setDepId(int depId) {
        this.depId = depId;
    }
    public String getDepName() {
        return this.depName;
    }
    
    public void setDepName(String depName) {
        this.depName = depName;
    }

    public String getDepPhone() {
        return depPhone;
    }

    public void setDepPhone(String depPhone) {
        this.depPhone = depPhone;
    }

    public Date getFounding() {
        return founding;
    }

    public void setFounding(Date founding) {
        this.founding = founding;
    }

    public String getLocation() {
        return location;
    }

    public void setLocation(String location) {
        this.location = location;
    }

    public String getFunctions() {
        return functions;
    }

    public void setFunctions(String functions) {
        this.functions = functions;
    }
    public Set<Employee> getEmployees() {
        return this.employees;
    }
    
    public void setEmployees(Set<Employee> employees) {
        this.employees = employees;
    }




}


