package bean;
// Generated Jun 2, 2017 3:55:32 PM by Hibernate Tools 4.3.1



import java.util.Date;

/**
 * Disciplinedetails generated by hbm2java
 */
public class Disciplinedetails implements java.io.Serializable{


     private int disdtId;
     private Discipline discipline;
     private Employee employee;
     private String reason;
     private Date date;
     private String formality;
    public Disciplinedetails() {
    }

	
    public Disciplinedetails(int disdtId, Discipline discipline, Employee employee) {
        this.disdtId = disdtId;
        this.discipline = discipline;
        this.employee = employee;
    }
    public Disciplinedetails(int disdtId, Discipline discipline, Employee employee, String reason, Date date, String formality) {
       this.disdtId = disdtId;
       this.discipline = discipline;
       this.employee = employee;
       this.reason = reason;
       this.date = date;
       this.formality=formality;
    }
   
    public int getDisdtId() {
        return this.disdtId;
    }
    
    public void setDisdtId(int disdtId) {
        this.disdtId = disdtId;
    }
    public Discipline getDiscipline() {
        return this.discipline;
    }
    
    public void setDiscipline(Discipline discipline) {
        this.discipline = discipline;
    }
    public Employee getEmployee() {
        return this.employee;
    }
    
    public void setEmployee(Employee employee) {
        this.employee = employee;
    }
    public String getReason() {
        return this.reason;
    }
    
    public void setReason(String reason) {
        this.reason = reason;
    }
    public Date getDate() {
        return this.date;
    }
    
    public void setDate(Date date) {
        this.date = date;
    }

    public String getFormality() {
        return formality;
    }

    public void setFormality(String formality) {
        this.formality = formality;
    }
    
   
    



}


