package bean;
// Generated Jun 2, 2017 3:55:32 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Discipline generated by hbm2java
 */
public class Discipline implements java.io.Serializable{


     private int disId;
     private String disName;
     private Set<Disciplinedetails> disciplinedetailses = new HashSet<Disciplinedetails>(0);

    public Discipline() {
    }

	
    public Discipline(int disId) {
        this.disId = disId;
    }
    public Discipline(int disId, String disName, Set<Disciplinedetails> disciplinedetailses) {
       this.disId = disId;
       this.disName = disName;
       this.disciplinedetailses = disciplinedetailses;
    }
   
    public int getDisId() {
        return this.disId;
    }
    
    public void setDisId(int disId) {
        this.disId = disId;
    }
    public String getDisName() {
        return this.disName;
    }
    
    public void setDisName(String disName) {
        this.disName = disName;
    }
    public Set<Disciplinedetails> getDisciplinedetailses() {
        return this.disciplinedetailses;
    }
    
    public void setDisciplinedetailses(Set<Disciplinedetails> disciplinedetailses) {
        this.disciplinedetailses = disciplinedetailses;
    }




}


