package bean;
// Generated Jun 2, 2017 3:55:32 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Reward generated by hbm2java
 */
public class Reward implements java.io.Serializable{


     private int rewId;
     private String rewname;
     private Set<Rewardetails> rewardetailses = new HashSet<Rewardetails>(0);

    public Reward() {
    }

	
    public Reward(int rewId) {
        this.rewId = rewId;
    }
    public Reward(int rewId, String rewname, Set<Rewardetails> rewardetailses) {
       this.rewId = rewId;
       this.rewname = rewname;
       this.rewardetailses = rewardetailses;
    }
   
    public int getRewId() {
        return this.rewId;
    }
    
    public void setRewId(int rewId) {
        this.rewId = rewId;
    }
    public String getRewname() {
        return this.rewname;
    }
    
    public void setRewname(String rewname) {
        this.rewname = rewname;
    }
    public Set<Rewardetails> getRewardetailses() {
        return this.rewardetailses;
    }
    
    public void setRewardetailses(Set<Rewardetails> rewardetailses) {
        this.rewardetailses = rewardetailses;
    }




}


